In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./Project_Data/4. Pandas_sales_data_1.csv" ,
                 encoding = 'UTF-8',
                 usecols= ['产品类别', '产品名称', '销售数量', '单价'])

In [3]:
df

    产品类别   产品名称  销售数量    单价
0   电子产品   智能手机     2  3999
1   服装鞋帽     T恤     5    89
2   食品饮料    纯牛奶    10    68
3   家居用品     台灯     3   159
4   办公耗材  A4打印纸     8    22
..   ...    ...   ...   ...
95  电子产品     耳机     4   199
96  服装鞋帽     西装     1  1299
97  食品饮料     奶粉     3   168
98  家居用品     花瓶     2    89
99  办公耗材     笔筒     7    25

[100 rows x 4 columns]

In [4]:
# 调取前几行，默认是 5
df.head(10)

   产品类别   产品名称  销售数量    单价
0  电子产品   智能手机     2  3999
1  服装鞋帽     T恤     5    89
2  食品饮料    纯牛奶    10    68
3  家居用品     台灯     3   159
4  办公耗材  A4打印纸     8    22
5  电子产品   蓝牙耳机     4   299
6  服装鞋帽    运动鞋     2   459
7  食品饮料    矿泉水    20    36
8  家居用品    收纳箱     6    79
9  办公耗材    中性笔    30     3

In [5]:
# 读取末尾，默认 5
df.tail()

    产品类别 产品名称  销售数量    单价
95  电子产品   耳机     4   199
96  服装鞋帽   西装     1  1299
97  食品饮料   奶粉     3   168
98  家居用品   花瓶     2    89
99  办公耗材   笔筒     7    25

In [6]:
# 对可统计列进行统计，并获取统计信息
df.head(10).describe().round(2)

        销售数量       单价
count  10.00    10.00
mean    9.00   521.30
std     9.12  1230.19
min     2.00     3.00
25%     3.25    44.00
50%     5.50    84.00
75%     9.50   264.00
max    30.00  3999.00

In [7]:
# 数据整体信息
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   产品类别    100 non-null    str
 1   产品名称    100 non-null    str
 2   销售数量    100 non-null    int64
 3   单价      100 non-null    int64
dtypes: int64(2), str(2)
memory usage: 5.2 KB

In [8]:
df['产品名称']

0      智能手机
1        T恤
2       纯牛奶
3        台灯
4     A4打印纸
      ...
95       耳机
96       西装
97       奶粉
98       花瓶
99       笔筒
Name: 产品名称, Length: 100, dtype: str

In [9]:
"""
基于行选择
    基于行号进行切片
        df.iloc[start : stop : step]
    基于索引进行切片
        df.loc[start : stop : step]

选择列
    df[['列1'， '列2', ...]]
    df['列']
"""

"\n基于行选择\n    基于行号进行切片\n        df.iloc[start : stop : step]\n    基于索引进行切片\n        df.loc[start : stop : step]\n\n选择列\n    df[['列1'， '列2', ...]]\n    df['列']\n"

In [10]:
# 列选取
df[['产品名称', '单价']]

     产品名称    单价
0    智能手机  3999
1      T恤    89
2     纯牛奶    68
3      台灯   159
4   A4打印纸    22
..    ...   ...
95     耳机   199
96     西装  1299
97     奶粉   168
98     花瓶    89
99     笔筒    25

[100 rows x 2 columns]

In [11]:
# 行选取，注意基于索引选取需要有索引，且索引必须有序，可为数字字母组合，字母是以ASCII为序
# 想要基于无序索引，必须输入索引列的准确内容
df.iloc[30 : 60 : 2]

    产品类别  产品名称  销售数量    单价
30  电子产品    相机     1  4999
32  食品饮料   巧克力     8    28
34  办公耗材    剪刀     5    12
36  服装鞋帽    卫衣     4   189
38  家居用品   晾衣架     6    35
40  电子产品   手机壳     8    39
42  食品饮料    饼干    10    18
44  办公耗材   回形针    50     2
46  服装鞋帽    风衣     2   599
48  家居用品    拖鞋     7    45
50  电子产品  智能手环     5   299
52  食品饮料     米     4    85
54  办公耗材    铅笔    40     2
56  服装鞋帽    夹克     2   429
58  家居用品   垃圾桶     8    29

In [12]:
df.loc[5 : 40 : 3]

    产品类别   产品名称  销售数量    单价
5   电子产品   蓝牙耳机     4   299
8   家居用品    收纳箱     6    79
11  服装鞋帽    羽绒服     2   899
14  办公耗材    文件夹    12     8
17  食品饮料     果汁     8    45
20  电子产品  笔记本电脑     1  5999
23  家居用品     地毯     2   369
26  服装鞋帽     短裤     4   129
29  办公耗材     胶水    10     5
32  食品饮料    巧克力     8    28
35  电子产品     音箱     3   499
38  家居用品    晾衣架     6    35

In [13]:
# 错误案例
df1 = pd.read_csv("./Project_Data/4. Pandas_sales_data_1.csv" ,
                 encoding = 'UTF-8',
                 usecols= ['产品类别', '产品名称', '销售数量', '单价'] ,
                 index_col = '单价')
df1.loc[0 : 5 : ]

KeyError: 'Cannot get left slice bound for non-monotonic index with a missing label 0. Either sort the index or specify an existing label.'

In [ ]:
# 索引必须唯一
df1.loc[159 : 2899 : 2]

In [14]:
"""
数据过滤
    单条件
        df[df['销售量'] >= 10]
        df[df['产品类别'] isin (['服饰', '食品'])]
        df[df['单价'].between(10, 50)]

    多条件
        并: &  或 : |
"""

"\n数据过滤\n    单条件\n        df[df['销售量'] >= 10]\n        df[df['产品类别'] isin (['服饰', '食品'])]\n        df[df['单价'].between(10, 50)]\n\n    多条件\n        并: &  或 : |\n"

In [15]:
df2 = pd.read_csv("./Project_Data/4. Pandas_sales_data_2.csv" , encoding = 'UTF-8')
df2

        订单号  产品类别   产品名称  销售数量    单价     货源    客户所在地      订单发起日期      订单结束日期
0   ORD-001  电子产品   智能手机     2  3999  深圳华强北   广东省深圳市  2026-01-05  2026-01-12
1   ORD-002  服装鞋帽     T恤     5    89  广州十三行   浙江省杭州市  2026-01-06  2026-01-10
2   ORD-003  食品饮料    纯牛奶    10    68  内蒙古牧场  上海市浦东新区  2026-01-07  2026-01-15
3   ORD-004  家居用品     台灯     3   159   中山古镇   江苏省南京市  2026-01-08  2026-01-14
4   ORD-005  办公耗材  A4打印纸     8    22  东莞造纸厂   北京市朝阳区  2026-01-09  2026-01-13
..      ...   ...    ...   ...   ...    ...      ...         ...         ...
95  ORD-096  电子产品     耳机     4   199  深圳科技园   河南省开封市  2026-04-10  2026-04-17
96  ORD-097  服装鞋帽     西装     1  1299   浙江宁波   安徽省淮南市  2026-04-11  2026-04-18
97  ORD-098  食品饮料     奶粉     3   168  内蒙古伊利   江西省新余市  2026-04-12  2026-04-19
98  ORD-099  家居用品     花瓶     2    89  江西景德镇   河北省保定市  2026-04-13  2026-04-20
99  ORD-100  办公耗材     笔筒     7    25   广东深圳   山西省运城市  2026-04-14  2026-04-21

[100 rows x 9 columns]

In [16]:
# 单项选择
df2[df2['销售数量'] >= 10]

        订单号  产品类别 产品名称  销售数量  单价     货源     客户所在地      订单发起日期      订单结束日期
2   ORD-003  食品饮料  纯牛奶    10  68  内蒙古牧场   上海市浦东新区  2026-01-07  2026-01-15
7   ORD-008  食品饮料  矿泉水    20  36   农夫山泉    湖北省武汉市  2026-01-12  2026-01-20
9   ORD-010  办公耗材  中性笔    30   3  温州文具厂    山东省济南市  2026-01-14  2026-01-16
12  ORD-013  食品饮料   薯片    15  12  上海食品厂    重庆市渝北区  2026-01-17  2026-01-21
14  ORD-015  办公耗材  文件夹    12   8   广东深圳    河南省郑州市  2026-01-19  2026-01-23
24  ORD-025  办公耗材  笔记本    15  12   广东广州    甘肃省兰州市  2026-01-29  2026-02-03
27  ORD-028  食品饮料  方便面    12   6  天津康师傅     西藏拉萨市  2026-02-01  2026-02-07
28  ORD-029  家居用品   衣架    20  15   浙江台州  内蒙古呼和浩特市  2026-02-02  2026-02-08
29  ORD-030  办公耗材   胶水    10   5   广东佛山     广西南宁市  2026-02-03  2026-02-09
41  ORD-042  服装鞋帽   袜子    25  15   浙江诸暨    辽宁省大连市  2026-02-15  2026-02-21
42  ORD-043  食品饮料   饼干    10  18   广东东莞    重庆市江北区  2026-02-16  2026-02-22
44  ORD-045  办公耗材  回形针    50   2  上海文具厂    河南省洛阳市  2026-02-18  2026-02-24
49  ORD-050  办公耗材  文件袋    20   6   广东广州    吉林省吉林市  2026-02-23  2026-03-01
54  ORD-055  办公耗材   铅笔    40   2   浙江义乌    山东省烟台市  2026-02-28  2026-03-06
59  ORD-060  办公耗材  橡皮擦    30   3  上海文具厂    陕西省咸阳市  2026-03-05  2026-03-12
64  ORD-065  办公耗材   尺子    10   5   广东深圳    河北省邯郸市  2026-03-10  2026-03-17
69  ORD-070  办公耗材  档案盒    12  10  宁波文具厂    浙江省嘉兴市  2026-03-15  2026-03-22
72  ORD-073  食品饮料   糖果    12  15  上海冠生园    湖南省岳阳市  2026-03-18  2026-03-25
79  ORD-080  办公耗材   信封    25   4  上海文具厂    安徽省安庆市  2026-03-25  2026-04-01
89  ORD-090  办公耗材  订书钉    20   3  宁波文具厂    湖南省湘潭市  2026-04-04  2026-04-11

In [ ]:
# 单项复合选择
# df2[(df2['销售数量'] >= 10) & (df2['销售数量'] <= 13) & (df2['单价'] <= 1000)]

# 用 between 简化
df2[(df2['销售数量'].between(10, 13)) & (df2['单价'] <= 1000)]

In [17]:
df2[
    ((df2['产品类别'].isin(['食品饮料'])) & (df2['销售数量'].between(5, 10, inclusive= 'neither'))) |
    ((df2['产品类别'].isin(['办公耗材'])) & (df2['销售数量'].between(10,15, inclusive= 'left')))
]

        订单号  产品类别  产品名称  销售数量  单价     货源      客户所在地      订单发起日期      订单结束日期
14  ORD-015  办公耗材   文件夹    12   8   广东深圳     河南省郑州市  2026-01-19  2026-01-23
17  ORD-018  食品饮料    果汁     8  45   北京汇源    河北省石家庄市  2026-01-22  2026-01-26
29  ORD-030  办公耗材    胶水    10   5   广东佛山      广西南宁市  2026-02-03  2026-02-09
32  ORD-033  食品饮料   巧克力     8  28   瑞士进口     广东省珠海市  2026-02-06  2026-02-10
37  ORD-038  食品饮料    酸奶     9  48   伊利集团     湖北省宜昌市  2026-02-11  2026-02-18
64  ORD-065  办公耗材    尺子    10   5   广东深圳     河北省邯郸市  2026-03-10  2026-03-17
67  ORD-068  食品饮料    面条     6  28   河南郑州  黑龙江省齐齐哈尔市  2026-03-13  2026-03-20
69  ORD-070  办公耗材   档案盒    12  10  宁波文具厂     浙江省嘉兴市  2026-03-15  2026-03-22
77  ORD-078  食品饮料  饼干礼盒     6  88  天津食品厂     辽宁省锦州市  2026-03-23  2026-03-30
82  ORD-083  食品饮料    面包     7  12  北京面包厂     山西省长治市  2026-03-28  2026-04-04
87  ORD-088  食品饮料    坚果     6  58   三只松鼠     福建省莆田市  2026-04-02  2026-04-09
92  ORD-093  食品饮料    果冻     8  12   广东潮汕     四川省南充市  2026-04-07  2026-04-14